### ISSUE TITLE
How to specify ssh-key

### ISSUE THREAD

**Issue by kostyrev** [GROG/ansible-role-user#1]
I don't get it.
Could you please provide an example.
Say, I want to create user tom with ssh_authorized_key='ssh-rsa AAAAB3N..."

**Comment by groggemans** [comment]
This role only manages the users and there private ssh-key, not there authorized ssh-keys.

To manage authorized ssh-keys you should use my [authorized-key](https://github.com/grog/ansible-role-authorized-key) role. It is designed to neatly work together with this user role (just like my [sudo](https://github.com/grog/ansible-role-sudo) role).

``` yaml
# specify your user settings
my_user_settings:
  name: user
  comment: Ansible
  shell: '/bin/bash'
  authorized_keys:
    - key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  sudo: # if you also use the sudo role
    hosts: ALL
    as: ALL
    commands: ALL
    nopasswd: yes

# pass this data to the different roles
user_list: "{{ my_user_settings }}"
authorized_key_list: "{{ my_user_settings }}"
sudo_list: "{{ my_user_settings }}"
```

My [management-user](https://github.com/grog/ansible-role-management-user) role combines these three roles in one easy to use role that manages everything about your user(s).

I'll add links in the readme of the roles to make things more clear.
Please let me know if this solves your problem!
